# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170413_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=1, default=52, max_digits=10),
            preserve_default=False,
        ),
    ]
