# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20170319_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(to='personal.Game')),
            ],
        ),
    ]
