# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(blank=True, to='personal.Tag'),
        ),
    ]
