# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20170412_1414'),
        ('personal', '0003_game_price'),
    ]

    operations = [
    ]
